[tool.black]
line-length = 88
target-version = ['py38']

[tool.yapf]
based_on_style = pep8
column_limit = 88

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 119
